"""push

Revision ID: 728cac6ea234
Revises: 
Create Date: 2026-07-06 20:49:40.737770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728cac6ea234'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('services', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),

    sa.Column('primary_image_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_image_object_key', sa.String(length=1024), nullable=True),
    sa.Column('primary_image_original_filename', sa.String(length=255), nullable=True),
    sa.Column('generated_headline', sa.String(length=255), nullable=True),
    sa.Column('generated_subheadline', sa.String(length=255), nullable=True),
    sa.Column('generated_description', sa.Text(), nullable=True),
    sa.Column('google_ad_headlines', sa.Text(), nullable=True),
    sa.Column('google_ad_descriptions', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.String(length=120), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_name'), 'businesses', ['business_name'], unique=False)
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_table('business_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('public_url', sa.String(length=2048), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_images_business_id'), 'business_images', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_images_id'), 'business_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_images_id'), table_name='business_images')
    op.drop_index(op.f('ix_business_images_business_id'), table_name='business_images')
    op.drop_table('business_images')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_name'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
